name: First Action
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 23f1003132@ds.study.iitm.ac.in
        run: echo "Hello, world!"
      - name: function_test
        run: python main.py
      
